name: Deploy to Server with SSH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up PHP and Composer for Laravel
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Adjust to your Laravel project's PHP version
          extensions: mbstring, intl, zip, sqlite3
          coverage: none

      # Step 3: Install Composer dependencies
      - name: Install Composer Dependencies
        run: |
          composer install

      # Step 4: Create .env file
      - name: Create .env file
        env:
          # Add all your Laravel environment variables here
          APP_KEY: ${{ secrets.APP_KEY }}
          # Add other necessary secrets
        run: |
          # Copy .env.example to .env
          cp .env.example .env
          
          # Set app key
          php artisan key:generate

          # Add other environment configurations
          echo "APP_KEY=$APP_KEY" >> .env
          # Add other environment variable configurations

      # Step 5: Prepare Laravel for deployment
      - name: Prepare Laravel for Deployment
        run: |
          # Clear config and cache
          php artisan config:clear
          php artisan cache:clear

          # Create deployment artifact
          mkdir -p deploy
          rsync -av --exclude='.git' --exclude='node_modules' --exclude='deploy' ./ deploy/

      # Step 6: Deploy to server using SSH
      - name: Deploy to Server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          DEPLOY_PATH: /var/www/html/oc.anichur.com
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Setup SSH
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts

          # Prepare server-side directory
          ssh -i ~/.ssh/id_rsa $USER@$HOST << EOF
            # Create deploy directory if not exists
            mkdir -p $DEPLOY_PATH
            
            # Set correct permissions
            sudo chown -R $USER:www-data $DEPLOY_PATH
            sudo chmod -R 755 $DEPLOY_PATH
          EOF

          # Deploy files with proper permissions
          rsync -avz --delete \
            -e "ssh -i ~/.ssh/id_rsa" \
            --chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r \
            ./deploy/ \
            $USER@$HOST:$DEPLOY_PATH/

          # Post-deployment server commands
          ssh -i ~/.ssh/id_rsa $USER@$HOST << EOF
            # Move to deploy directory
            cd $DEPLOY_PATH

            # Set correct Laravel permissions
            sudo chown -R $USER:www-data storage
            sudo chown -R $USER:www-data bootstrap/cache
            sudo chmod -R 775 storage
            sudo chmod -R 775 bootstrap/cache

            # Install Composer dependencies on server
            composer install --no-dev --no-interaction

            # Run Laravel specific commands
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache

            # Optional: Restart web server if needed
            sudo systemctl restart nginx
            # Or for Apache: sudo systemctl restart apache2
          EOF